version: '3.7'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - backend_network

  backend:
    build: ./backend
    container_name: backend
#    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn -c gunicorn.py project.wsgi
    command: gunicorn project.wsgi:application -w 4 --bind 0.0.0.0:80
    volumes:
      - ./backend/:/usr/src/app/
      - ./backend/static/:/usr/src/app/static/
      - ./backend/media/:/usr/src/app/media/
    ports:
      - 5000:80
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - backend_network
      - nginx_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 8000:80
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static/:/dist/static/
      - ./backend/media/:/dist/media/
#      - ./logs/nginx-access.log:/var/log/nginx/access.log
#      - ./logs/nginx-error.log:/var/log/nginx/error.log
    links:
      - backend
    depends_on:
      - db
      - backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  backend_network:
    driver: bridge

#volumes:
#  pgdata:
#  static_volume:
#  media_volume:
